Update

diff --git a/archi/forsys/logic/packmisc b/archi/forsys/logic/packmisc
--- a/archi/forsys/logic/packmisc
+++ b/archi/forsys/logic/packmisc
@@ -6,56 +6,48 @@ ipacs () {
 cd $idir
 pnum=$(cat "$plist" | wc -l)
 msg "${BOLD}pacman will install $pnum packages, this will take a bit${CLS}.."
-
 if [ "$pverbose" = "false" ]; then
 echo -n "Installing."
 fi
-
 while read set; do
- if [ "$pverbose" = "true" ]; then
+if [ "$pverbose" = "true" ]; then
 echo -n "[$pnum] Installing $set..."
 ((pacman -Sy --noconfirm --noprogressbar "$set" > /dev/null 2>&1) && echo ".okay.") || echo ".failed!"
- else
+else
 ((pacman -Sy --noconfirm --noprogressbar "$set" > /dev/null 2>&1) && echo -n ".") || echo -n "!"
- fi
+fi
 let pnum--
 done < "$plist"
-
 if [ "$pverbose" = "false" ]; then
 echo ".okay."
 fi
 }
-
 iflats () {
 cd "$idir"
 echo -n "Install flatpak..."
-(pacman -Sy --noconfirm --noprogressbar flatpak > /dev/null 2>&1) || echo ".Failed to install flatpak!" 
+(pacman -Sy --noconfirm --noprogressbar flatpak > /dev/null 2>&1) || echo ".Failed to install flatpak!"
 echo ".okay."
 echo -n "Add flatpak repo [flathub]..."
 (flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo > /dev/null 2>&1) && echo ".okay."
 fnum=$(cat "$flist" | wc -l)
 msg "${BOLD}flatpak will install $fnum apps, this will take a while${CLS}.."
-
 if [ "$fverbose" = "false" ]; then
 echo -n "Installing."
 fi
-
 while read set; do
 shortset=$(echo "$set" | rev | cut -d. -f1 | rev | cut -d/ -f1)
- if [ "$fverbose" = "true" ]; then
+if [ "$fverbose" = "true" ]; then
 echo -n "[$fnum] Installing $shortset..."
-((flatpak install --noninteractive -y "$set" > /dev/null 2>&1) && echo ".okay.") || (flatpak install --noninteractive -y --or-update "$set" > /dev/null 2>&1 &&  echo ".retry okay.") || echo "...retry failed!"
- else
-((flatpak install --noninteractive -y "$set" > /dev/null 2>&1) && echo -n ".") || (flatpak install --noninteractive -y --or-update "$set" > /dev/null 2>&1 &&  echo -n "..") || echo -n "!!"
- fi
+((flatpak install --noninteractive -y "$set" > /dev/null 2>&1) && echo ".okay.") || (flatpak install --noninteractive -y --or-update "$set" > /dev/null 2>&1 && echo ".retry okay.") || echo "...retry failed!"
+else
+((flatpak install --noninteractive -y "$set" > /dev/null 2>&1) && echo -n ".") || (flatpak install --noninteractive -y --or-update "$set" > /dev/null 2>&1 && echo -n "..") || echo -n "!!"
+fi
 let fnum--
 done < "$flist"
-
 if [ "$fverbose" = "false" ]; then
 echo ".okay."
 fi
 }
-
 imods () {
 ##install kmods
 echo -n "Install kernel modules [$mlist]..."
@@ -66,8 +58,6 @@ done < "$mlist"
 fi
 echo ".okay."
 }
-
-
 repac () {
 cd $idir
 pnum=$(cat "$rlist" | wc -l)
@@ -78,5 +68,3 @@ echo -n " Removing [$set."
 let pnum--
 done < "$rlist"
 }
-
-
